# Generated by Django 3.2.12 on 2023-03-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('user_type', models.CharField(choices=[('hr', 'HR'), ('emp', 'EMPLOYEE'), ('bde', 'BDE')], max_length=20)),
            ],
        ),
    ]
