# Generated by Django 3.2.12 on 2023-03-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='createUser',
            new_name='createUserModel',
        ),
    ]
