# Generated by Django 3.2.12 on 2023-03-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_rename_createuser_createusermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusermodel',
            name='user_type',
            field=models.CharField(choices=[('hr', 'HR'), ('emp', 'EMPLOYEE'), ('bde', 'BDE'), ('peon', 'PEON')], max_length=20),
        ),
    ]
