# Generated by Django 3.2.12 on 2023-03-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0003_alter_createusermodel_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createusermodel',
            name='user_type',
        ),
    ]
