# Generated by Django 3.2.12 on 2023-03-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0004_remove_createusermodel_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='createusermodel',
            name='user_type',
            field=models.CharField(choices=[('hr', 'HR'), ('emp', 'EMPLOYEE'), ('bde', 'BDE'), ('peon', 'PEON')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
