# Generated by Django 3.2.12 on 2023-03-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0005_createusermodel_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusermodel',
            name='user_type',
            field=models.CharField(choices=[('HR', 'hr'), ('EMPLOYEE', 'emp'), ('BDE', 'bde'), ('PEON', 'peon')], max_length=20),
        ),
    ]
