# Generated by Django 3.2.12 on 2023-03-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0007_loginusermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginusermodel',
            old_name='email',
            new_name='email_id',
        ),
    ]
