# Generated by Django 3.2.12 on 2023-03-31 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0008_rename_email_loginusermodel_email_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createUserModel',
        ),
        migrations.DeleteModel(
            name='loginUserModel',
        ),
    ]
